development: 
  adapter : postgresql
  database: freuder_development
  encoding: unicode
  pool: 5
  timeout: 5000
  username: freuder_dev
  password: 123456789

test: 
  adapter : postgresql
  database: freuder_test
  encoding: unicode
  pool: 5
  timeout: 5000
  username: freuder_dev
  password: 123456789

production:
  adapter: postgresql
  encoding: utf8
  database: freuder_production
  pool: 5
